In [23]:
import random

import tensorflow as tf

### There are different ways to create tensors in TensorFlow.

We will see three of them:

1. tf.constant
2. tf.Variable
3. tf.range

In [2]:
# tf.constant
a_constant = tf.constant([1, 2, 3, 4, 5, 6])
a_constant

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

In [3]:
# tf.Variable
a_variable = tf.Variable([1, 2, 3, 4, 5, 6])
a_variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

even though (constant & Variable) have the same input and both are tensors, they are different.

+ tf.constant: cannot be cahnged, is inmutable.
+ tf.Variable: it can be reassigned in te future, is mutable.

In [4]:
# tf.range
a_range = tf.range(start=1, limit=7)
a_range

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6])>

If we see the outputs of the three different ways to create a tensor we can conclude that the output of *a_constant* and *a_range* is exactly the same and is slightly different to *a_variable*, but none of these are the same, the difference is clearer when we work with **tensor operations**. We will start with **tensor rank**.

# Tensor Rank

The rank of a tensor identifies the number of dimentions of that tensor.

+ Scalar: it's a quantity that has magnitude but no direction.
+ Vector: it's a quantity that has magnitude and direction.
+ Matrix: it's an array of numbers arranged in rows and columns.
+ Tensor: $$\{x \mid x \in \mathbb{Z}, 3 \leq x\}$$

In [5]:
# scalar
a = tf.constant(1)
a

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
# vector
b = tf.constant([1.2, 2.3, 3.4, 4.5])
b

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1.2, 2.3, 3.4, 4.5], dtype=float32)>

In [7]:
# matrix
c = tf.constant([[1, 2], [3, 4]])
c

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [8]:
# 3-dimentional tensor
d = tf.constant([[[23, 45], [9, 11], [47, 12]], [[90, 1], [88, 0], [2, 99]]])
d

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[23, 45],
        [ 9, 11],
        [47, 12]],

       [[90,  1],
        [88,  0],
        [ 2, 99]]])>

# Properties of tensors

Lets us explore how to interpret tensor outputs in detail. We will learn how to identify the key properties of a tensor, from its printed representation.

When we print a tensor it displays the variable name, shape and data type.

Thus far, we utilized default arguments when creating tensors. Lets us make some adjustments to see how this changes the output.

In [9]:
# scalar
a_scalar = tf.Variable(1.1, name='TDC', dtype='float16')
a_scalar

<tf.Variable 'TDC:0' shape=() dtype=float16, numpy=1.1>

By leveraging TensorFlow functions, we can get more information about a tensor. Here we are going to use the **tf.rank()** function to inspect the rank of a tensor.

In [10]:
# scalar
a = tf.constant(1.1)

# vector
b = tf.constant([1.2, 2.3, 3.4, 4.5])

# matrix
c = tf.constant([[25, 11], [9, 0]])

# Generating tesor rank
print(f'The rank of the scalar is: {tf.rank(a).numpy()}')
print(f'The rank of the vector is: {tf.rank(b)}')
print(f'The rank of the matrix is: {tf.rank(c)}')

The rank of the scalar is: 0
The rank of the vector is: 1
The rank of the matrix is: 2


In [11]:
# Another way to get the rank of a tensor
print(f'The dimention of the scalar is : {a.ndim}')
print(f'The dimention of the vector is: {b.ndim}')
print(f'The dimention of the matrix is: {c.ndim}')

The dimention of the scalar is : 0
The dimention of the vector is: 1
The dimention of the matrix is: 2


If we want to get the data type of a tensor we use the **dtype** argument.

In [12]:
print(f'The data type of the scalar is: {a.dtype}')
print(f'The data type of the vector is: {b.dtype}')
print(f'The data type of the matrix is: {c.dtype}')

The data type of the scalar is: <dtype: 'float32'>
The data type of the vector is: <dtype: 'float32'>
The data type of the matrix is: <dtype: 'int32'>


Now, we will see the shape of the tensors.

+ The scalar has no shape value.
+ The vector has a shape value of one unit.
+ The matrix has a shape value of two units.

In [13]:
print(f'The shape of the scalar is: {a.shape}')
print(f'The shape of the vector is: {b.shape}')
print(f'The shape of the matrix is: {c.shape}')

The shape of the scalar is: ()
The shape of the vector is: (4,)
The shape of the matrix is: (2, 2)


Now we will compute the number of elements in each tensor.

In [14]:
# Generating number of elements in a tensor
print(f'The Size of the scalar is: {tf.size(a).numpy()}')
print(f'The Size of the vector is: {tf.size(b)}')
print(f'The Size of the matrix is: {tf.size(c)}')

The Size of the scalar is: 1
The Size of the vector is: 4
The Size of the matrix is: 4


### Basic tensor operations

One big hurdle with learning TensorFlow is understanding what tensor operations are and why we need them. Tensors are fundamental data structures in TensorFlow and they van be used for **store**, **manipulate** and **analyze** data in ML models.

### Changing data types

In [15]:
a = tf.constant([1, 2, 3, 4, 5])
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [16]:
a = tf.cast(a, dtype=tf.float32)
a

<tf.Tensor: shape=(5,), dtype=float32, numpy=array([1., 2., 3., 4., 5.], dtype=float32)>

### Indexing

In [17]:
# Creatinga 2 x 2 matrix
a = tf.constant([[1, 2], [3, 4]], dtype='float32')
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [18]:
# What if we want extract some information from the matrix?
# How we do it?
# We can apply indexing to get desired information
# Indexing
print(a[0])
print()
print(a[0][1])

tf.Tensor([1. 2.], shape=(2,), dtype=float32)

tf.Tensor(2.0, shape=(), dtype=float32)


Indexing using **tf.slice()** function.

In [19]:
c = tf.constant([44, 11, 0, 1, 29, 10, 99, 81])
print(tf.slice(c, begin=[3], size=[3]))

tf.Tensor([ 1 29 10], shape=(3,), dtype=int32)


### Expanding a matrix

Let us look at how to expand the dimension of a matrix

In [20]:
a

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [21]:
tf.expand_dims(a, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[1., 2.],
        [3., 4.]]], dtype=float32)>

In [22]:
(tf.expand_dims(a, axis=0)).shape, (tf.expand_dims(a, axis=1)).shape, (tf.expand_dims(a, axis=-1)).shape

(TensorShape([1, 2, 2]), TensorShape([2, 1, 2]), TensorShape([2, 2, 1]))

### Tensor aggregation

In [26]:
random.seed(22)
a = random.sample(range(1, 100), 50)
a = tf.constant(a)
a

<tf.Tensor: shape=(50,), dtype=int32, numpy=
array([18, 32,  4, 79, 58, 24, 90, 16, 84, 45, 11, 30, 35,  7, 41, 77, 23,
       71, 56, 86, 74,  3, 76, 34, 40, 54, 25, 94, 15, 68,  8, 42, 43, 91,
       72, 51, 20, 95, 50, 81, 70, 33, 10, 99, 53, 60, 67, 93, 12, 28])>

Let's say we want to find the smallest number in our tensor, maually read it would be difficult, what if out range of values was up a thousands or a millon?

With TensorFlow we can find not just the minimum in one strike but we can also find the maximum value, the sum of all values, the mean, and much more.

In [30]:
print(f'The smallest number in our vector is: {tf.reduce_min(a).numpy()}')
print(f'The largest number in our vector is: {tf.reduce_max(a)}')
print(f'The sum of our vector is: {tf.reduce_sum(a)}')
print(f'The mean of our vector is: {tf.reduce_mean(a)}')

The smallest number in our vector is: 3
The largest number in our vector is: 99
The sum of our vector is: 2448
The mean of our vector is: 48


In [31]:
# What if we want to find the position that holds the minimum and maximum values in a vector?
print(f'The position that holds the lowest value is: {tf.argmin(a)}')
print()
print(f'The position that holds the largest value is: {tf.argmax(a)}')

The position that holds the lowest value is: 21

The position that holds the largest value is: 43


In [39]:
a[21].numpy(), a[43].numpy()

(3, 99)